---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность на странице корзины удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность видеть на странице товара и в каталоге название, рейтинг, цену со скидкой и без нее
  - Корзина будет хранится в сессии браузера
  - Интернет-магазин будет являться SPA-приложением
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен иметь мобильную версию
  - Сайт должен быть совместим с последними версиями браузеров
implicit:
  - Интуитивно понятная навигация и структура интернет-магазина
  - Невозможность заказа отрицательного количества товара
  - Невозможность ввода отрицательной цены товара
  - У товаров должны присутствовать изображения
  - Должна присутствовать возможность сбросить все варианты фильтрации не перезагружая страницу
