---
functional:
  - Интернет-магазин будет являться SPA-приложением
  - На странице товара и в каталоге должны отображаться название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность на странице корзины удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - Корзина должна хранится в сессии браузера
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit:
  - Интуитивно понятная навигация и структура интернет-магазина
  - Невозможность заказа отрицательного количества товара
  - Невозможность ввода отрицательной цены товара
  - У товаров должны присутствовать изображения
  - Должна присутствовать возможность сбросить все варианты фильтрации не перезагружая страницу
